/**
 * System Constants and Default Configuration
 */

export const APP_CONSTANTS = {
  APP_NAME: 'Bitbucket PR Approver Local',
  APP_VERSION: '1.0.0',
  DEFAULT_PORT: 3100,
  DEFAULT_HOST: '127.0.0.1', // Strictly local loopback binding for security
  
  STORAGE: {
    DEFAULT_DATA_DIR: '.bitbucket-pr-approver-data',
    CONFIG_FILE: 'config.json',
    JOBS_FILE: 'jobs.json',
    LOGS_FILE: 'logs.json',
    SECRET_KEY_FILE: 'master.key',
  },

  SCHEDULER: {
    MIN_INTERVAL_SECONDS: 10,
    MAX_INTERVAL_SECONDS: 86400, // 24 hours
    DEFAULT_INTERVAL_SECONDS: 60,
    MAX_CONCURRENT_JOBS: 3,
    PR_FETCH_LIMIT: 50,
  },

  BITBUCKET: {
    CLOUD_BASE_URL: 'https://api.bitbucket.org/2.0',
    DEFAULT_TIMEOUT_MS: 15000,
    MAX_RETRY_ATTEMPTS: 2,
    RETRY_DELAY_MS: 1000,
  },

  CACHE: {
    // Cache approved PR IDs in memory to eliminate redundant requests within window
    APPROVED_PR_CACHE_TTL_MS: 24 * 60 * 60 * 1000, // 24 hours
    MAX_CACHE_ENTRIES: 1000,
  },

  LOGS: {
    MAX_STORED_LOGS: 300,
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,
  },
} as const;

export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  BITBUCKET_UNREACHABLE: 'BITBUCKET_UNREACHABLE',
  VPN_REQUIRED: 'VPN_REQUIRED',
  SSL_CERTIFICATE_ERROR: 'SSL_CERTIFICATE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  RATE_LIMITED: 'RATE_LIMITED',
  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
  INSUFFICIENT_SCOPES: 'INSUFFICIENT_SCOPES',
  IP_ALLOWLIST: 'IP_ALLOWLIST',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  CONFIG_MISSING: 'CONFIG_MISSING',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  GENERIC_API_ERROR: 'GENERIC_API_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
